1. Use the API to get all available data for the GDP per capita, PPP (constant 2017 international $) indicator. Hint: this indicator has code "NY.GDP.PCAP.PP.KD". Adjust the query parameters so that you can retrieve all available rows. Convert the results to a DataFrame.

In [186]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import json
import time

In [138]:
endpoint = 'https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD?format=json&per_page=17556'
response = requests.get(endpoint)

In [139]:
res = response.json()[1]

In [140]:
gdp_df = pd.DataFrame(res)

In [141]:
gdp_df.drop(columns=['indicator'], inplace=True)

In [142]:
pd.json_normalize(gdp_df['country'])

       id                        value
0      ZH  Africa Eastern and Southern
1      ZH  Africa Eastern and Southern
2      ZH  Africa Eastern and Southern
3      ZH  Africa Eastern and Southern
4      ZH  Africa Eastern and Southern
...    ..                          ...
17551  ZW                     Zimbabwe
17552  ZW                     Zimbabwe
17553  ZW                     Zimbabwe
17554  ZW                     Zimbabwe
17555  ZW                     Zimbabwe

[17556 rows x 2 columns]

In [46]:
gdp_df = pd.merge(pd.json_normalize(gdp_df['country']).rename(columns={'value': 'country'}), gdp_df.drop(columns=['country', 'unit', 'obs_status', 'decimal']), left_index=True, right_index=True)

In [49]:
gdp_df.rename(columns={'value':'gdp_per_capita'}, inplace=True)

In [50]:
gdp_df

       id                      country countryiso3code  date  gdp_per_capita
0      ZH  Africa Eastern and Southern             AFE  2025             NaN
1      ZH  Africa Eastern and Southern             AFE  2024     4106.434140
2      ZH  Africa Eastern and Southern             AFE  2023     4083.993003
3      ZH  Africa Eastern and Southern             AFE  2022     4106.501907
4      ZH  Africa Eastern and Southern             AFE  2021     4056.113017
...    ..                          ...             ...   ...             ...
17551  ZW                     Zimbabwe             ZWE  1964             NaN
17552  ZW                     Zimbabwe             ZWE  1963             NaN
17553  ZW                     Zimbabwe             ZWE  1962             NaN
17554  ZW                     Zimbabwe             ZWE  1961             NaN
17555  ZW                     Zimbabwe             ZWE  1960             NaN

[17556 rows x 5 columns]

2. Now, use the API to get all available data for Life expectancy at birth, total (years). This indicator has code "SP.DYN.LE00.IN". Again, convert the results to a DataFrame.

In [54]:
endpoint = 'https://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN?format=json&per_page=17556'
response = requests.get(endpoint)

In [59]:
life_expectancy_df = pd.DataFrame(response.json()[1])

In [61]:
life_expectancy_df.drop(columns=['indicator'], inplace=True)

In [67]:
life_expectancy_df = pd.merge(pd.json_normalize(life_expectancy_df['country']).rename(columns={'value': 'country'}), life_expectancy_df.drop(columns=['country', 'unit', 'obs_status', 'decimal']), left_index=True, right_index=True)

In [70]:
life_expectancy_df.rename(columns={'value':'life_exprectancy'}, inplace=True)

In [71]:
life_expectancy_df

       id                      country countryiso3code  date  life_exprectancy
0      ZH  Africa Eastern and Southern             AFE  2025               NaN
1      ZH  Africa Eastern and Southern             AFE  2024         65.349930
2      ZH  Africa Eastern and Southern             AFE  2023         65.146228
3      ZH  Africa Eastern and Southern             AFE  2022         64.487152
4      ZH  Africa Eastern and Southern             AFE  2021         62.979999
...    ..                          ...             ...   ...               ...
17551  ZW                     Zimbabwe             ZWE  1964         55.431000
17552  ZW                     Zimbabwe             ZWE  1963         54.942000
17553  ZW                     Zimbabwe             ZWE  1962         54.453000
17554  ZW                     Zimbabwe             ZWE  1961         53.966000
17555  ZW                     Zimbabwe             ZWE  1960         53.492000

[17556 rows x 5 columns]

3. Merge the two results DataFrames together. You may want to rename or drop columns prior to merging.

In [73]:
gdp_df.drop(columns=['id'], inplace=True)

In [75]:
life_expectancy_df.drop(columns=['id'], inplace=True)

In [77]:
gdp_life = pd.merge(gdp_df, life_expectancy_df)

In [111]:
gdp_life

,country,countryiso3code,date,gdp_per_capita,life_exprectancy
0,Africa Eastern and Southern,AFE,2025,NaN,NaN
1,Africa Eastern and Southern,AFE,2024,4106.434140,65.349930
2,Africa Eastern and Southern,AFE,2023,4083.993003,65.146228
3,Africa Eastern and Southern,AFE,2022,4106.501907,64.487152
4,Africa Eastern and Southern,AFE,2021,4056.113017,62.979999
...,...,...,...,...,...
17551,Zimbabwe,ZWE,1964,NaN,55.431000
17552,Zimbabwe,ZWE,1963,NaN,54.942000
17553,Zimbabwe,ZWE,1962,NaN,54.453000
17554,Zimbabwe,ZWE,1961,NaN,53.966000
17555,Zimbabwe,ZWE,1960,NaN,53.492000

4. You can also get more information about the available countries (region, capital city, income level classification, etc.) by using the Country API. Use this API to pull in all available data. Merge this with your other datasets. Use this to now remove the rows that correspond to regions and not countries.

In [83]:
endpoint = 'https://api.worldbank.org/v2/country/all?format=json&per_page=296'
response = requests.get(endpoint)

In [87]:
countries = pd.DataFrame(response.json()[1])

In [95]:
countries

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,AFG,AF,Afghanistan,"{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,AFR,A9,Africa,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,AFW,ZI,Africa Western and Central,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
...,...,...,...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
292,YEM,YE,"Yemen, Rep.","{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352
293,ZAF,ZA,South Africa,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746
294,ZMB,ZM,Zambia,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982
295,ZWE,ZW,Zimbabwe,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312

In [97]:
countries = pd.merge(pd.json_normalize(countries['region']).rename(columns={'id':'region_id', 'value':'region'}).drop(columns=['iso2code']), countries.drop(columns=['region']), left_index=True, right_index=True)

In [100]:
countries

,region_id,region,id,iso2Code,name,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,LCN,Latin America & Caribbean,ABW,AW,Aruba,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,NA,Aggregates,AFE,ZH,Africa Eastern and Southern,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,MEA,"Middle East, North Africa, Afghanistan & Pakistan",AFG,AF,Afghanistan,"{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,NA,Aggregates,AFR,A9,Africa,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,NA,Aggregates,AFW,ZI,Africa Western and Central,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
...,...,...,...,...,...,...,...,...,...,...,...
291,NA,Aggregates,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,"{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
292,MEA,"Middle East, North Africa, Afghanistan & Pakistan",YEM,YE,"Yemen, Rep.","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352
293,SSF,Sub-Saharan Africa,ZAF,ZA,South Africa,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746
294,SSF,Sub-Saharan Africa,ZMB,ZM,Zambia,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982
295,SSF,Sub-Saharan Africa,ZWE,ZW,Zimbabwe,"{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312

In [108]:
countries = pd.merge(countries.drop(columns=['incomeLevel', 'adminregion', 'lendingType']), pd.json_normalize(countries['incomeLevel']).rename(columns={'value':'income_level'}).drop(columns=['id', 'iso2code']), left_index=True, right_index=True)

In [113]:
countries_gdp_life = pd.merge(countries, gdp_life, left_on='name', right_on='country')

In [118]:
countries_gdp_life.drop(columns=['name', 'iso2Code'], inplace=True)

In [122]:
cols = ['countryiso3code', 'country', 'region_id', 'region', 'capitalCity', 'longitude', 'latitude', 'income_level', 'date', 'gdp_per_capita', 'life_exprectancy']

In [123]:
countries_gdp_life.loc[:, cols]

,countryiso3code,country,region_id,region,capitalCity,longitude,latitude,income_level,date,gdp_per_capita,life_exprectancy
0,ABW,Aruba,LCN,Latin America & Caribbean,Oranjestad,-70.0167,12.5167,High income,2025,NaN,NaN
1,ABW,Aruba,LCN,Latin America & Caribbean,Oranjestad,-70.0167,12.5167,High income,2024,44558.928759,76.500
2,ABW,Aruba,LCN,Latin America & Caribbean,Oranjestad,-70.0167,12.5167,High income,2023,41964.771191,76.353
3,ABW,Aruba,LCN,Latin America & Caribbean,Oranjestad,-70.0167,12.5167,High income,2022,38979.835825,76.226
4,ABW,Aruba,LCN,Latin America & Caribbean,Oranjestad,-70.0167,12.5167,High income,2021,35104.786804,73.655
...,...,...,...,...,...,...,...,...,...,...,...
17419,ZWE,Zimbabwe,SSF,Sub-Saharan Africa,Harare,31.0672,-17.8312,Lower middle income,1964,NaN,55.431
17420,ZWE,Zimbabwe,SSF,Sub-Saharan Africa,Harare,31.0672,-17.8312,Lower middle income,1963,NaN,54.942
17421,ZWE,Zimbabwe,SSF,Sub-Saharan Africa,Harare,31.0672,-17.8312,Lower middle income,1962,NaN,54.453
17422,ZWE,Zimbabwe,SSF,Sub-Saharan Africa,Harare,31.0672,-17.8312,Lower middle income,1961,NaN,53.966
17423,ZWE,Zimbabwe,SSF,Sub-Saharan Africa,Harare,31.0672,-17.8312,Lower middle income,1960,NaN,53.492

In [124]:
countries_gdp_life = countries_gdp_life.loc[:, cols]

In [127]:
countries_gdp_life.rename(columns={'life_exprectancy': 'life_expectancy'}, inplace=True)

In [135]:
countries_gdp_life = countries_gdp_life[countries_gdp_life['region'] != 'Aggregates']

In [144]:
countries_gdp_life[countries_gdp_life.country == ('United States')]

,countryiso3code,country,region_id,region,capitalCity,longitude,latitude,income_level,date,gdp_per_capita,life_expectancy
16434,USA,United States,NAC,North America,Washington D.C.,-77.032,38.8895,High income,2025,NaN,NaN
16435,USA,United States,NAC,North America,Washington D.C.,-77.032,38.8895,High income,2024,75489.266433,78.890244
16436,USA,United States,NAC,North America,Washington D.C.,-77.032,38.8895,High income,2023,74158.716416,78.385366
16437,USA,United States,NAC,North America,Washington D.C.,-77.032,38.8895,High income,2022,72679.257540,77.434146
16438,USA,United States,NAC,North America,Washington D.C.,-77.032,38.8895,High income,2021,71307.401728,76.329268
...,...,...,...,...,...,...,...,...,...,...,...
16495,USA,United States,NAC,North America,Washington D.C.,-77.032,38.8895,High income,1964,NaN,70.165854
16496,USA,United States,NAC,North America,Washington D.C.,-77.032,38.8895,High income,1963,NaN,69.917073
16497,USA,United States,NAC,North America,Washington D.C.,-77.032,38.8895,High income,1962,NaN,70.119512
16498,USA,United States,NAC,North America,Washington D.C.,-77.032,38.8895,High income,1961,NaN,70.270732
16499,USA,United States,NAC,North America,Washington D.C.,-77.032,38.8895,High income,1960,NaN,69.770732

### Bonus Questions:
1. Adjust your request so that it returns data just for the United States.

In [260]:
endpoint = 'https://api.worldbank.org/v2/country/usa/indicator/NY.GDP.PCAP.PP.KD?format=json&per_page=100'
response = requests.get(endpoint)

In [263]:
gdp_usa = pd.DataFrame(response.json()[1])

In [264]:
gdp_usa

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2025,NaN,,,0
1,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2024,75489.266433,,,0
2,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2023,74158.716416,,,0
3,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2022,72679.257540,,,0
4,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2021,71307.401728,,,0
...,...,...,...,...,...,...,...,...
61,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,1964,NaN,,,0
62,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,1963,NaN,,,0
63,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,1962,NaN,,,0
64,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,1961,NaN,,,0
65,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,1960,NaN,,,0

2. Adjust your request so that it returns data just for the United States for the year 2021.

In [265]:
endpoint = 'https://api.worldbank.org/v2/country/usa/indicator/NY.GDP.PCAP.PP.KD?format=json&per_page=100&date=2021'
response = requests.get(endpoint)

In [266]:
gdp_usa_2021 = pd.DataFrame(response.json()[1])

In [267]:
gdp_usa_2021

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2021,71307.401728,,,0

3. Adjust your request so that it returns data just for the United States for the years 2000 through 2021.

In [268]:
endpoint = 'https://api.worldbank.org/v2/country/usa/indicator/NY.GDP.PCAP.PP.KD?format=json&per_page=100&date=2000:2021'
response = requests.get(endpoint)

In [269]:
gdp_usa_2000_2021 = pd.DataFrame(response.json()[1])

In [270]:
gdp_usa_2000_2021

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2021,71307.401728,,,0
1,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2020,67342.070929,,,0
2,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2019,69112.602689,,,0
3,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2018,67719.765639,,,0
4,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2017,66155.555568,,,0
5,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2016,65017.654964,,,0
6,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2015,64359.472590,,,0
7,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2014,63018.803394,,,0
8,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2013,61958.723442,,,0
9,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2012,61134.530609,,,0
10,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2011,60245.484399,,,0
11,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2010,59789.412907,,,0
12,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2009,58714.973692,,,0
13,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2008,60798.433840,,,0
14,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2007,61306.596939,,,0
15,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2006,60676.565569,,,0
16,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2005,59604.753637,,,0
17,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2004,58131.633685,,,0
18,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2003,56498.207831,,,0
19,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2002,55436.116981,,,0
20,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2001,55017.304979,,,0
21,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2000,55038.622496,,,0

4. Adjust your request so that it returns data for the United States and Canada for the years 2000 through 2021.

In [271]:
endpoint = 'https://api.worldbank.org/v2/country/usa;can/indicator/NY.GDP.PCAP.PP.KD?format=json&per_page=100&date=2000:2021'
response = requests.get(endpoint)

In [272]:
gdp_usa_can_2000_2021 = pd.DataFrame(response.json()[1])

In [273]:
gdp_usa_can_2000_2021

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2021,56995.117678,,,0
1,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2020,54092.879032,,,0
2,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2019,57583.845798,,,0
3,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2018,57337.490910,,,0
4,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2017,56612.328537,,,0
5,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2016,55606.154919,,,0
6,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2015,55660.867527,,,0
7,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2014,55723.483540,,,0
8,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2013,54712.178424,,,0
9,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2012,54034.803475,,,0
10,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2011,53681.129670,,,0
11,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2010,52558.440814,,,0
12,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2009,51552.422384,,,0
13,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2008,53711.679206,,,0
14,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2007,53761.862030,,,0
15,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2006,53195.781842,,,0
16,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2005,52356.557804,,,0
17,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2004,51210.679612,,,0
18,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2003,50139.786235,,,0
19,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2002,49695.006691,,,0
20,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2001,48774.167553,,,0
21,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'CA', 'value': 'Canada'}",CAN,2000,48399.305539,,,0
22,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2021,71307.401728,,,0
23,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2020,67342.070929,,,0
24,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2019,69112.602689,,,0
25,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2018,67719.765639,,,0
26,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2017,66155.555568,,,0
27,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2016,65017.654964,,,0
28,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2015,64359.472590,,,0
29,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2014,63018.803394,,,0
30,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2013,61958.723442,,,0
31,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2012,61134.530609,,,0
32,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2011,60245.484399,,,0
33,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2010,59789.412907,,,0
34,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2009,58714.973692,,,0
35,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2008,60798.433840,,,0
36,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2007,61306.596939,,,0
37,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2006,60676.565569,,,0
38,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2005,59604.753637,,,0
39,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2004,58131.633685,,,0
40,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2003,56498.207831,,,0
41,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2002,55436.116981,,,0
42,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2001,55017.304979,,,0
43,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'US', 'value': 'United States'}",USA,2000,55038.622496,,,0

5. If you haven't already done so and you would like to get some additional practice using loops, use the page parameter in order to pull all records. Do not change the value of the per_page parameter. You will likely need to utilize a loop of some kind in order to pull all records.

In [287]:
endpoint = 'https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD?format=json'
response = requests.get(endpoint)

In [288]:
pages = response.json()[0]['pages']

In [289]:
data = response.json()[1]

In [1]:
# data

In [291]:
for i in range(2, pages+1):
    while True:
        try:
            endpoint = f'https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD?format=json&page={i}'
            response = requests.get(endpoint)
            data += response.json()[1]
            break
        except json.JSONDecodeError:
            continue

In [303]:
# data = data[50:]

In [300]:
data_df = pd.DataFrame(data)

In [302]:
data_df

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,NaN,,,0
1,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,4106.434140,,,0
2,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,4083.993003,,,0
3,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,4106.501907,,,0
4,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,4056.113017,,,0
...,...,...,...,...,...,...,...,...
17551,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1964,NaN,,,0
17552,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1963,NaN,,,0
17553,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1962,NaN,,,0
17554,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1961,NaN,,,0
17555,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1960,NaN,,,0

6. The endpoint "http://api.worldbank.org/v2/indicator" will return information about all available indicators. See Indicator API Queries. Use this endpoint to find the code for the "Public Expenditure on Education (% GDP)" indicator.

In [274]:
endpoint2 = "http://api.worldbank.org/v2/indicator?format=json&per_page=30000"
response2 = requests.get(endpoint2)

In [2]:
# response2.json()

In [276]:
indicators = pd.DataFrame(response2.json()[1])

In [277]:
indicators

,id,name,unit,source,sourceNote,sourceOrganization,topics
0,1.0.HCount.1.90usd,Poverty Headcount ($1.90 a day),,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
1,1.0.HCount.2.5usd,Poverty Headcount ($2.50 a day),,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
2,1.0.HCount.Mid10to50,Middle Class ($10-50 a day) Headcount,,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
3,1.0.HCount.Ofcl,Official Moderate Poverty Rate-National,,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of data from Nation...,"[{'id': '11', 'value': 'Poverty '}]"
4,1.0.HCount.Poor4uds,Poverty Headcount ($4 a day),,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
...,...,...,...,...,...,...,...
29495,ytil_some_dfcl_all,Youth idle rate (% of persons with some degree...,,"{'id': '92', 'value': 'Disability Data Hub (DD...",,,[]
29496,ytil_some_dfcl_fem,Youth idle rate (% of female persons with some...,,"{'id': '92', 'value': 'Disability Data Hub (DD...",,,[]
29497,ytil_some_dfcl_male,Youth idle rate (% of male persons with some d...,,"{'id': '92', 'value': 'Disability Data Hub (DD...",,,[]
29498,ytil_some_dfcl_rur,Youth idle rate (% of persons living in rural ...,,"{'id': '92', 'value': 'Disability Data Hub (DD...",,,[]
29499,ytil_some_dfcl_urb,Youth idle rate (% of persons living in urban ...,,"{'id': '92', 'value': 'Disability Data Hub (DD...",,,[{}]

In [278]:
indicators.loc[indicators.name.str.contains('Public Expenditure on Education', regex=False), 'id']

24993    SE.XPD.EDUC.ZS
Name: id, dtype: object